/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthBooksRouteImport } from './routes/_auth/books'
import { Route as AuthBookNewRouteImport } from './routes/_auth/book.new'
import { Route as AuthBookIdRouteImport } from './routes/_auth/book.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthBooksRoute = AuthBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBookNewRoute = AuthBookNewRouteImport.update({
  id: '/book/new',
  path: '/book/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBookIdRoute = AuthBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/books': typeof AuthBooksRoute
  '/login': typeof PublicLoginRoute
  '/book/$id': typeof AuthBookIdRoute
  '/book/new': typeof AuthBookNewRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/books': typeof AuthBooksRoute
  '/login': typeof PublicLoginRoute
  '/book/$id': typeof AuthBookIdRoute
  '/book/new': typeof AuthBookNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/books': typeof AuthBooksRoute
  '/_public/login': typeof PublicLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/book/$id': typeof AuthBookIdRoute
  '/_auth/book/new': typeof AuthBookNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books' | '/login' | '/book/$id' | '/book/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books' | '/login' | '/book/$id' | '/book/new'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/books'
    | '/_public/login'
    | '/_auth/'
    | '/_auth/book/$id'
    | '/_auth/book/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/books': {
      id: '/_auth/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthBooksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/book/new': {
      id: '/_auth/book/new'
      path: '/book/new'
      fullPath: '/book/new'
      preLoaderRoute: typeof AuthBookNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/book/$id': {
      id: '/_auth/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthBookIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBooksRoute: typeof AuthBooksRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthBookIdRoute: typeof AuthBookIdRoute
  AuthBookNewRoute: typeof AuthBookNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBooksRoute: AuthBooksRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthBookIdRoute: AuthBookIdRoute,
  AuthBookNewRoute: AuthBookNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
