server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Vite build: index + assets
    location / {
        try_files $uri /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }
}