basePath: /api/v1
definitions:
  models.Account:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      profile:
        $ref: '#/definitions/models.Profile'
      updated_at:
        type: string
    type: object
  models.Profile:
    properties:
      account_id:
        type: integer
      avatar:
        type: string
      bio:
        type: string
      created_at:
        type: string
      full_name:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  types.CommonResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  types.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.SignUpDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  title: My API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      responses:
        "200":
          description: Thành công
          schema:
            allOf:
            - $ref: '#/definitions/types.CommonResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Login user by name
      tags:
      - auth
  /auth/me:
    get:
      responses:
        "200":
          description: Thành công
          schema:
            allOf:
            - $ref: '#/definitions/types.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Account'
              type: object
      security:
      - BearerAuth: []
      summary: Get current user info
      tags:
      - auth
  /auth/signup:
    post:
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.SignUpDto'
      responses:
        "200":
          description: Thành công
          schema:
            allOf:
            - $ref: '#/definitions/types.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Account'
              type: object
      summary: create a user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type only token (not include Bearer)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
