basePath: /api/v1
definitions:
  dtos.RequestChangePassword:
    properties:
      email:
        type: string
    type: object
  dtos.ResetPassword:
    properties:
      email:
        type: string
      new_password:
        type: string
      token:
        type: string
    type: object
  dtos.VerifyOTP:
    properties:
      email:
        type: string
      otp:
        type: string
    type: object
  models.Account:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      profile:
        $ref: '#/definitions/models.Profile'
    type: object
  models.Profile:
    properties:
      account_id:
        type: integer
      avatar:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.CommonResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  types.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  types.SignUpDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  title: My API
  version: "1.0"
paths:
  /auth/ask-reset-password:
    post:
      parameters:
      - description: email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.RequestChangePassword'
      responses: {}
      summary: send otp to email ask change password
      tags:
      - auth
  /auth/login:
    post:
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      responses: {}
      summary: Login user by name
      tags:
      - auth
  /auth/me:
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: Get current user info
      tags:
      - auth
  /auth/reset-password:
    post:
      parameters:
      - description: new password
        in: body
        name: reset-password
        required: true
        schema:
          $ref: '#/definitions/dtos.ResetPassword'
      responses: {}
      summary: change password with the singed token
      tags:
      - auth
  /auth/signup:
    post:
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.SignUpDto'
      responses:
        "200":
          description: Thành công
          schema:
            allOf:
            - $ref: '#/definitions/types.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Account'
              type: object
      summary: create a user
      tags:
      - auth
  /auth/verify-OTP:
    post:
      parameters:
      - description: OTP code
        in: body
        name: verifyOTP
        required: true
        schema:
          $ref: '#/definitions/dtos.VerifyOTP'
      responses: {}
      summary: Verify OTP
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type only token (not include Bearer)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
