version: '3.8'

services:
  backend:
    build: .
    restart: always
    # Không cần mở port 8080 ra ngoài nữa, Caddy sẽ quản lý
    expose:
      - "8080"

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from api.docluon.com --to backend:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: