# ===== DEV STAGE =====
FROM golang:1.25.5-alpine AS dev
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .
CMD ["air"]

# ===== BUILD STAGE =====
FROM golang:1.25.5-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app

# ===== PROD STAGE =====
FROM alpine:latest AS prod
WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8080
CMD ["./app"]
