INSERT INTO categories (id, name, created_at, updated_at) VALUES
                                                              ('ton-giao', 'Tôn giáo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('triet-hoc', 'Triết học', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('van-hoc', 'Văn học', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('tieu-thuyet', 'Tiểu thuyết', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('trinh-tham-hinh-su', 'Trinh thám - Hình sự', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('kinh-di-giat-gan', 'Kinh dị - Giật gân', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('tho-ca', 'Thơ ca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('truyen-cuoi', 'Truyện cười', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('co-tich-thieu-nhi', 'Cổ tích - Thiếu nhi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('kiem-hiep', 'Kiếm hiệp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('truyen-ngan-tan-van', 'Truyện ngắn - Tản văn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('lich-su-dia-ly-chinh-tri', 'Lịch sử - Địa lý - Chính trị', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('khoa-hoc-xa-hoi', 'Khoa học xã hội', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('khoa-hoc-cong-nghe', 'Khoa học - Công nghệ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('phap-luat', 'Pháp luật', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('phat-trien-ban-than', 'Phát triển bản thân', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('giao-duc-hoc-tap', 'Giáo dục - Học tập', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('ban-hang-marketing', 'Bán hàng - Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('kinh-doanh-quan-tri', 'Kinh doanh - Quản trị', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('khoi-nghiep', 'Khởi nghiệp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('tu-truyen-hoi-ki', 'Tự truyện - Hồi kí', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('tieu-su', 'Tiểu sử', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('khac', 'Khác', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);