INSERT OR IGNORE INTO tags (id, name, description, created_at) VALUES
(101, 'Trẻ em', 'Đối tượng trẻ em', CURRENT_TIMESTAMP),
(102, 'Tuổi teen', 'Đối tượng tuổi mới lớn', CURRENT_TIMESTAMP),
(200, 'Kinh điển', 'Các tác phẩm văn học kinh điển', CURRENT_TIMESTAMP),
(301, 'Nobel', 'Tác phẩm đoạt giải Nobel', CURRENT_TIMESTAMP),
(302, 'Booker', 'Tác phẩm đoạt giải Booker', CURRENT_TIMESTAMP),
(400, 'Chuyển thể', 'Tác phẩm được chuyển thể thành phim', CURRENT_TIMESTAMP),
(501, 'Cổ đại', 'Bối cảnh hoặc nội dung cổ đại', CURRENT_TIMESTAMP),
(502, 'Hiện đại', 'Bối cảnh hoặc nội dung hiện đại', CURRENT_TIMESTAMP),
(601, 'Cười thoải mái', 'Nội dung hài hước, vui vẻ', CURRENT_TIMESTAMP),
(602, 'Suy ngẫm', 'Nội dung sâu sắc, triết lý', CURRENT_TIMESTAMP),
(603, 'Bài giảng', 'Nội dung mang tính giáo dục, bài học', CURRENT_TIMESTAMP),
(604, 'Lãng mạn', 'Câu chuyện tình yêu lãng mạn', CURRENT_TIMESTAMP),
(605, 'Hồi hộp', 'Cảm giác hồi hộp, chờ đợi', CURRENT_TIMESTAMP),
(606, 'Hấp dẫn', 'Nội dung lôi cuốn người đọc', CURRENT_TIMESTAMP),
(607, 'Tuổi học trò', 'Câu chuyện về thời học sinh', CURRENT_TIMESTAMP),
(608, 'Giải trí', 'Nội dung mang tính chất giải trí nhẹ nhàng', CURRENT_TIMESTAMP),
(609, 'Gay cấn', 'Nội dung kịch tính, dồn dập', CURRENT_TIMESTAMP),
(610, 'Câu chuyện hấp dẫn', 'Cốt truyện được xây dựng tốt', CURRENT_TIMESTAMP),
(611, 'Thế giới huyền ảo', 'Bối cảnh fantasy, kỳ ảo', CURRENT_TIMESTAMP),
(612, 'Mafia', 'Nội dung về thế giới ngầm', CURRENT_TIMESTAMP),
(613, 'Huyền bí', 'Yếu tố bí ẩn, chưa có lời giải', CURRENT_TIMESTAMP),
(614, 'Trinh thám', 'Nội dung phá án, suy luận', CURRENT_TIMESTAMP);