/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0
 */
import type { ModelsAccount } from "./modelsAccount";
import type { TypesCommonResponse } from "./typesCommonResponse";

export type GetAuthMe200 = TypesCommonResponse & {
  data?: ModelsAccount;
};
