/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0
 */
import type { ModelsProfile } from "./modelsProfile";

export type ModelsAccount = {
  created_at?: string;
  email?: string;
  id?: number;
  name?: string;
  profile?: ModelsProfile;
  updated_at?: string;
};
