/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0
 */

export type ModelsProfile = {
  account_id?: number;
  avatar?: string;
  bio?: string;
  created_at?: string;
  full_name?: string;
  id?: number;
  updated_at?: string;
};
